# -*- coding: utf-8 -*-
"""análise_series_temporais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18wgFpCEMMtAPZe2Adc2jH-GOdIGfu8mW

# Importação de biblioteca
"""

import pandas as pd

import yfinance as yf

import matplotlib.pyplot as plt

from prophet import Prophet

"""O Prophet é uma ferramenta desenvolvida pelo Facebook para fazer previsões em séries temporais, que são basicamente dados coletados ao longo do tempo, como os preços das ações. É famoso por ser fácil de usar e por funcionar bem mesmo com poucos dados ou com dados que possuem padrões irregulares, o que é comum no mercado de ações.

# Empresa Johnson & Johnson

desde 2020 até o final de 2023
"""

dados = yf.download("JNJ", start="2020-01-01", end="2023-12-31", progress=False)
dados.reset_index()

"""Agora, dividimos nossos dados em duas partes: uma para treinar nosso 'adivinho' digital, que é até julho de 2023, e outra para testar nossas previsões, que é o restante do ano.

# Modelagem
- Dados treinamento
- Dados teste
"""

dados_treino = dados[dados['Date'] < '2023-07-31']
dados_teste = dados[dados['Date'] >= '2023-07-31']

"""Preparação dos parametros do modelo"""

dados_prophet_treino = dados_treino[['Date', 'Close']].rename(columns={'Date': 'ds', 'Close': 'y'})

"""Criação do modelo Prophet
- Considerar padrões semanais e anuais nos dados
- Não considerar dados diários
- Considerar feriados dos EUA
"""

modelo = Prophet(weekly_seasonality=True,
        yearly_seasonality=True,
        daily_seasonality=False)

modelo.add_country_holidays(country_name='US')

"""Treinamento do modelo"""

modelo.fit(dados_prophet_treino)

"""Criação de dados para prever o futuro
- até o final de 2023
"""

futuro = modelo.make_future_dataframe(periods=150)

"""Previsão"""

previsao = modelo.predict(futuro)

"""# Visualização
- Linha azul mostra o preço real das ações até julho de 2023
- Linha verde mostra os preços reais após essa data
- Linha laranja mostra o que o Prophet previu
- Linha vermelha pontilhada marca onde começam as previsões
"""

plt.figure(figsize=(14, 8))
plt.plot(dados_treino['Date'], dados_treino['Close'], label='Dados de Treino', color='blue')
plt.plot(dados_teste['Date'], dados_teste['Close'], label='Dados Reais (Teste)', color='green')
plt.plot(previsao['ds'], previsao['yhat'], label='Previsão', color='orange', linestyle='--')

plt.axvline(dados_treino['Date'].max(), color='red', linestyle='--', label='Início da Previsão')
plt.xlabel('Data')
plt.ylabel('Preço de Fechamento')
plt.title('Previsão de Preço de Fechamento vs Dados Reais')
plt.legend()
plt.show()